version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rails
    versions:
    - 6.0.3.5
  - dependency-name: newrelic_rpm
    versions:
    - 6.15.0
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 5.0.0
  - dependency-name: skylight
    versions:
    - 4.3.2
    - 5.0.0
  - dependency-name: autoprefixer-rails
    versions:
    - 10.2.0.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
